"""Session identity and titles.

Loading a session continues in that file (it becomes the current session, so
later saves never overwrite the session that was open before); settings-only
sessions are not written; startup restores the newest session with a
conversation.  Titles are generated by the model while idle, refreshed every
_TITLE_EVERY turns, and a /title set by the user is never overwritten.
"""
import json
import os
import tempfile
import time
import unittest
from pathlib import Path
from unittest import mock

import harness.controller as cmod
import harness.harness as hmod
from harness import session as session_mod
from harness.commands import handle as handle_command
from harness.llm.base import ChatResponse, LLMClient


class FakeClient(LLMClient):
    provider_name = "fake"
    replies: list = []          # title replies, popped per chat(); an Exception is raised
    calls = 0

    def chat(self, messages, tools, think=None, num_ctx=None, on_delta=None):
        FakeClient.calls += 1
        reply = FakeClient.replies.pop(0) if FakeClient.replies else "ok"
        if isinstance(reply, Exception):
            raise reply
        return ChatResponse(content=reply, done_reason="stop")

    def context_length(self):
        return 32768

    def list_models(self):
        return ["fake"]

    def abort(self):
        pass


def fake_client(*a, **k):
    return FakeClient("http://fake", "fake")


class _Base(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.home = Path(self.tmp.name)
        FakeClient.replies, FakeClient.calls = [], 0
        self._patches = [
            mock.patch.dict(os.environ, {"HOME": str(self.home)}),   # Logger uses Path.home()
            mock.patch.object(session_mod, "_PREFS_PATH", self.home / "prefs.json"),
            mock.patch.object(session_mod, "SESSION_DIR", self.home / "sessions"),
            mock.patch.object(hmod, "make_client", fake_client),
            mock.patch.object(cmod, "make_client", fake_client),
        ]
        for p in self._patches:
            p.start()
        self.h = self.new_harness()

    def tearDown(self):
        self.h.logger.close()
        for p in self._patches:
            p.stop()
        self.tmp.cleanup()

    def new_harness(self):
        return hmod.Harness(host="http://fake", model="fake", workdir=self.home)

    def converse(self, h, text="hi", reply="hello"):
        h.messages += [{"role": "user", "content": text}, {"role": "assistant", "content": reply}]
        h._turn_count += 1


class SessionIdentity(_Base):
    def saved(self, name):
        return json.loads((session_mod.SESSION_DIR / f"{name}.json").read_text())

    def test_load_adopts_the_loaded_file(self):
        self.converse(self.h, "first session")
        self.h._autosave()
        a = self.h.session_path()
        b = self.new_harness()
        b._ts = "2000-01-01T00-00-00"      # an older session
        self.converse(b, "second session")
        b._autosave()
        b.logger.close()

        self.h.load_session(b.session_path())
        self.assertEqual(self.h.session_path(), b.session_path())
        self.assertEqual(self.h.logger._path.stem, b._ts)
        self.converse(self.h, "more")
        self.h._autosave()
        # The session that was open before is untouched; the loaded one grows.
        self.assertEqual(self.saved(a.stem)["messages"][1]["content"], "first session")
        self.assertEqual(len(self.saved(b._ts)["messages"]), 5)

    def test_load_saves_the_open_session_first(self):
        self.converse(self.h, "unsaved")
        other = session_mod.session_path("2000-01-01T00-00-00")
        session_mod.atomic_write(other, json.dumps({"messages": [
            {"role": "system", "content": "s"}, {"role": "user", "content": "old"}]}))
        name = self.h.session_path().stem
        self.h.load_session(other)
        self.assertEqual(self.saved(name)["messages"][1]["content"], "unsaved")

    def test_settings_only_session_is_not_written(self):
        handle_command("/run-confirm on", self.h)
        self.h._autosave()
        self.assertFalse(self.h.session_path().exists())
        self.assertIn("model", session_mod.load_prefs())

    def test_latest_session_skips_empty_and_broken(self):
        self.converse(self.h, "real")
        self.h._ts = "2001-01-01T00-00-00"
        self.h._autosave()
        session_mod.atomic_write(session_mod.session_path("2002-01-01T00-00-00"),
                                 json.dumps({"messages": [{"role": "system", "content": "s"}]}))
        session_mod.atomic_write(session_mod.session_path("2003-01-01T00-00-00"), "{broken")
        self.assertEqual(session_mod.latest_session().stem, "2001-01-01T00-00-00")


class CleanTitle(unittest.TestCase):
    def test_cleaning(self):
        c = hmod.clean_title
        self.assertEqual(c('"Fix the parser."\n'), "Fix the parser")
        self.assertEqual(c("<think>hmm</think>\n\n## Title: **Web UI sessions**\nextra"),
                         "Web UI sessions")
        self.assertEqual(c(""), "")
        self.assertEqual(len(c("word " * 40)), hmod._TITLE_MAX_LEN)


class TitleGeneration(_Base):
    def setUp(self):
        super().setUp()
        self.h.idle_recap = False
        self.c = cmod.Controller(self.h)

    def idle(self):
        self.c._last_activity = time.monotonic() - cmod._TITLE_IDLE - 1
        self.c._idle_tick()

    def test_title_after_first_reply_then_every_n_turns(self):
        self.converse(self.h)
        FakeClient.replies = ["Greeting the model"]
        self.idle()
        self.assertEqual(self.h.title, "Greeting the model")
        self.assertEqual(json.loads(self.h.session_path().read_text())["title"],
                         "Greeting the model")
        FakeClient.replies = ["Later title"]
        for _ in range(cmod._TITLE_EVERY - 1):
            self.converse(self.h)
            self.idle()
        self.assertEqual(self.h.title, "Greeting the model")
        self.converse(self.h)
        self.idle()
        self.assertEqual(self.h.title, "Later title")

    def test_not_while_recently_active(self):
        self.converse(self.h)
        self.c._last_activity = time.monotonic()
        self.c._idle_tick()
        self.assertEqual(FakeClient.calls, 0)

    def test_failure_is_not_retried_until_a_new_turn(self):
        self.converse(self.h)
        FakeClient.replies = [RuntimeError("down")]
        self.idle()
        self.idle()
        self.assertEqual((self.h.title, FakeClient.calls), ("", 1))
        self.converse(self.h)
        FakeClient.replies = ["Recovered"]
        self.idle()
        self.assertEqual(self.h.title, "Recovered")

    def test_user_title_is_locked(self):
        self.converse(self.h)
        handle_command("/title My own name", self.h)
        for _ in range(cmod._TITLE_EVERY + 1):
            self.converse(self.h)
            self.idle()
        self.assertEqual((self.h.title, FakeClient.calls), ("My own name", 0))
        handle_command("/title auto", self.h)
        FakeClient.replies = ["Model name"]
        self.idle()
        self.assertEqual(self.h.title, "Model name")

    def test_off_setting(self):
        handle_command("/session-titles off", self.h)
        self.converse(self.h)
        self.idle()
        self.assertEqual(FakeClient.calls, 0)
        self.assertFalse(session_mod.load_prefs()["session_titles"])

    def test_new_session_clears_and_load_restores(self):
        self.converse(self.h)
        FakeClient.replies = ["Kept title"]
        self.idle()
        path = self.h.session_path()
        self.h.new_session()
        self.assertEqual(self.h.title, "")
        self.h.load_session(path)
        self.assertEqual(self.h.title, "Kept title")
        self.assertEqual(self.h.status_event().title, "Kept title")


if __name__ == "__main__":
    unittest.main()
