"""momo companion art and speech lines, shared by the TUI and the web UI."""
from __future__ import annotations

_MOMO_WR = [   # walking right — two alternating leg frames
    ["\\    /\\ ", " )  ( ')", "( ¯¯  ) ", " /\\/\\/\\ "],
    ["\\    /\\ ", " )  ( ')", "( ¯¯  ) ", " \\/\\/\\/ "],
]
_MOMO_WL = [   # walking left — two alternating leg frames
    [" /\\   \\ ", "(' )  ( ", "(  ¯¯ ) ", " /\\/\\/\\ "],
    [" /\\   \\ ", "(' )  ( ", "(  ¯¯ ) ", " \\/\\/\\/ "],
]
_MOMO_SIT = [  # sitting — normal, blink
    ["\\    /\\ ", " )  ( ')", "(  /  ) ", " \\(__)| "],
    ["\\    /\\ ", " )  ( -)", "(  /  ) ", " \\(__)| "],
]
_MOMO_SIT_L = [  # sitting facing left — normal, blink
    [" /\\   \\ ", "(' )  ( ", "(  \\  ) ", "|(__)/ "],
    [" /\\   \\ ", "(- )  ( ", "(  \\  ) ", "|(__)/ "],
]
_MOMO_WR_BLINK = ["\\    /\\ ", " )  ( -)", "(  ¯  ) ", " /\\/\\/\\ "]  # walking-right blink
_MOMO_WL_BLINK = [" /\\   \\ ", "(' )  ( ", "(  ¯  ) ", " /\\/\\/\\ "]  # walking-left blink
# key: (mode, is_thinking)  value: list of strings each ≤ 25 visible chars
_SPEECH_TEXTS: dict[tuple[str, bool], list[str]] = {
    ("coding",  False): [
        "< mew~", "< purrr", "< found a bug!",
        "< git commit!", "< tests pass?", "< grep is love",
        "< ship it!", "< refactor?", "< code review!",
        "< off by one!", "< vim or emacs?",
        "< lgtm!", "< rubber duck?",
        "< dry it up!", "< lint errors!",
        "< push to main?", "< branch first!",
        "< stash it!", "< rebase time!",
        "< merge conflict?", "< squash it!",
        "< todo fixme!", "< purrr~",
        "< hot reload?", "< benchmarks!",
        "< profiler!", "< coverage!",
        "< make clean?", "< chmod +x!",
        "< mew mew~",
    ],
    ("coding",  True): [
        "< mew?", "< compiling...", "< stack trace!",
        "< segfault...", "< null pointer!",
        "< linker error!", "< undefined!",
        "< syntax error?", "< type mismatch",
        "< core dumped!", "< infinite loop?",
        "< race condition?", "< deadlock...",
        "< heap overflow!", "< bus error!",
        "< stack overflow!", "< exception!",
        "< unhandled err!", "< oom killed...",
        "< traceback!", "< mew...",
        "< assertion fail", "< divide by zero?",
        "< abi mismatch!", "< memory leak...",
        "< watchdog!", "< panic!",
        "< signal caught!", "< debugger...",
        "< step through?",
    ],
    ("design",  False): [
        "< mew~", "< nice api!", "< solid design!",
        "< decouple it!", "< dry principle",
        "< event driven?", "< schema first!",
        "< purrr", "< interface?", "< abstract it!",
        "< single concern", "< clean code!",
        "< patterns!", "< microservices?",
        "< idempotent!", "< immutable!",
        "< hexagonal?", "< monolith?",
        "< async!", "< solid!",
        "< loose coupling", "< extension pts?",
        "< separation?", "< dependency inj?",
        "< pure functions?", "< state machine?",
        "< event sourcing?", "< cqrs?",
        "< mew mew~", "< purrr~",
    ],
    ("design",  True): [
        "< mew mew mew", "< hmm...", "< thinking hard",
        "< trade-offs...", "< let me think",
        "< edge cases!", "< iterate!",
        "< coupling...", "< dependency?",
        "< mew?", "< complexity...",
        "< layering...", "< contracts!",
        "< invariants...", "< mew mew",
        "< abstractions?", "< modelling...",
        "< boundaries?", "< purrr...",
        "< cohesion?", "< simplify...",
        "< risk analysis?", "< first principles",
        "< tech debt...", "< scope creep?",
        "< bottleneck?", "< scalability?",
        "< feedback loop?", "< mew~",
        "< purrr~",
    ],
    ("chat",    False): [
        "< tell me more!", "< interesting!", "< got it!",
        "< ooh!", "< makes sense!", "< mew~",
        "< say more!", "< purrr", "< keep going!",
        "< I see!", "< right right!", "< nice!",
        "< elaborate?", "< and then?", "< really?",
        "< noted!", "< curious!", "< for sure!",
        "< neat!", "< love it!", "< mhm!",
        "< yep!", "< ah ha!", "< go on!",
        "< understood!", "< mew mew~", "< clever!",
        "< fascinating!", "< ok ok!", "< purrr~",
    ],
    ("chat",    True): [
        "< reading...", "< let me check", "< searching...",
        "< hmm...", "< found it!", "< scanning...",
        "< parsing...", "< mew?", "< cross-checking",
        "< grepping...", "< hold on...", "< one sec...",
        "< digging in...", "< inspecting!", "< ah interesting",
        "< found a ref", "< following up", "< tracing it...",
        "< mew mew?", "< mapping it...", "< connecting dots",
        "< hmm hmm...", "< checking...", "< pattern match!",
        "< got a clue!", "< narrowing...", "< almost there",
        "< verifying...", "< cross ref...", "< purrr...",
    ],
    ("plan",    False): [
        "< what's the plan?", "< mew~", "< step by step!",
        "< checklist!", "< purrr", "< plan approved?",
        "< one step at a time", "< ready when you are", "< looks solid!",
        "< tick tick!", "< mew mew~", "< measure twice",
        "< cut once!", "< y to run it!", "< edit the plan?",
        "< any feedback?", "< read it first!", "< good goal!",
        "< small steps!", "< tests last?", "< /plan run?",
        "< plan saved!", "< approve pls?", "< nice & tidy!",
        "< all boxes [x]!", "< plan complete!", "< what's next?",
        "< bug or feature?", "< tell me more!", "< purrr~",
    ],
    ("plan",    True): [
        "< investigating...", "< sniff sniff", "< tracing...",
        "< step done?", "< checking box!", "< following plan",
        "< hmm...", "< next step!", "< reproducing...",
        "< mapping it...", "< verifying...", "< purrr...",
        "< root cause?", "< found the bug!", "< reading code...",
        "< grepping...", "< writing steps...", "< [~] in progress",
        "< ticking [x]!", "< which step now?", "< stay on track!",
        "< no step skip!", "< complete_step!", "< revise plan?",
        "< running tests...", "< almost done!", "< hmm hmm...",
        "< one more step", "< mew?", "< *checks list*",
    ],
    ("momo",   False): [
        "< mew~", "< purrr~", "< hi there!",
        "< whatcha doing?", "< ooh!", "< shiny!",
        "< sniff sniff", "< found a bug?", "< cuddle break?",
        "< mew mew~", "< sunny spot!", "< outside?",
        "< zoomies!", "< nap time?", "< treat?",
        "< bird outside!", "< *chirps*", "< brrp!",
        "< purrr purrr", "< headbutt!", "< mew!",
        "< you okay?", "< proud of you!", "< good job!",
        "< mew mew mew", "< *kneads*", "< snooze...",
        "< i'm here!", "< tell me more!", "< oh no!",
        "< mew~",
    ],
    ("momo",   True): [
        "< reading...", "< sniff sniff", "< hmm...",
        "< looking...", "< mew?", "< found it?",
        "< scanning...", "< curious...", "< one sec...",
        "< *stares*", "< parsing...", "< mew mew?",
        "< digging in!", "< hold on...", "< oh interesting",
        "< following...", "< tracing...", "< almost!",
        "< mew...", "< inspecting!", "< got a clue!",
        "< cross ref...", "< hmm hmm", "< checking...",
        "< purrr...", "< nearly there", "< ah!",
        "< verifying...", "< *sniffs file*", "< mew!",
    ],
}
_SPEECH_TEXTS_DEFAULT = ["< mew~", "< purrr", "< mew mew"]  # fallback for unknown modes
